# Generated by Django 3.2.7 on 2021-11-25 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=50)),
                ('deuda', models.IntegerField(default=0)),
                ('telefono', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id_detalle', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_hora_entrega', models.DateTimeField()),
                ('fecha_hora_entrega_real', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=20)),
                ('contrasena', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('numero_tarj', models.IntegerField(primary_key=True, serialize=False)),
                ('dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modelo.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('num_servicio', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_reserva_servicio', models.DateTimeField()),
                ('fecha_inicio_servicio', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modelo.cliente')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modelo.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField()),
                ('hora_pago', models.TimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modelo.cliente')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modelo.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id_incidente', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_incidente', models.DateTimeField()),
                ('observacion', models.TextField(max_length=10000)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modelo.detalle')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modelo.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id_elemento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=15)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_retiro', models.DateField()),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modelo.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleElemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modelo.detalle')),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modelo.elemento')),
            ],
        ),
        migrations.AddField(
            model_name='detalle',
            name='elementos',
            field=models.ManyToManyField(through='Modelo.DetalleElemento', to='Modelo.Elemento'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modelo.servicio'),
        ),
    ]
